[workspace]
authors = ["Luigi Freda <luigifreda@gmail.com>"]
channels = ["conda-forge"]
name = "dlplay"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.11.9"
pip = ">=25.2,<26"
numpy = ">=2.3.2,<3"
opencv = ">=4.12.0,<5"
matplotlib = ">=3.10.5,<4"
jax = ">=0.7.0,<0.8"
pytorch = ">=2.7.1,<3"
scipy = ">=1.16.0,<2"
scikit-learn = "*"

[tool.pixi.pip-dependencies]
opencv-python = "*"
opencv-contrib-python = "*"


[tool.setuptools]
packages = ["dlplay"]

[tool.setuptools.package-dir]
dlplay = "dlplay"